name       : haskell-contravariant
version    : 1.4
release    : 1
source     :
    - http://hackage.haskell.org/package/contravariant-1.4/contravariant-1.4.tar.gz : e1666df1373ed784baa7d1e8e963bbc2d1f3c391578ac550ae74e7399173ee84
license    : BSD-3-Clause
component  : programming.haskell
summary    : Contravariant functors
description: |
    Contravariant functors
builddeps  :
    - haskell-cabal-install
    - haskell-StateVar
    - haskell-transformers-compat
    - haskell-void
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register

