name       : haskell-contravariant
version    : 1.4.1
release    : 2
source     :
    - https://hackage.haskell.org/package/contravariant-1.4.1/contravariant-1.4.1.tar.gz : c93d3d619fa378f3fdf92c53bb8b04b8f47963b88aba7cfa54b57656189ad0ed
license    : BSD-3-Clause
component  : programming.haskell
summary    : Contravariant functors
description: |
    Contravariant functors
builddeps  :
    - haskell-cabal-install
    - haskell-StateVar
    - haskell-transformers-compat
    - haskell-void
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register

