name       : haskell-contravariant
version    : 1.5.2
release    : 3
source     :
    - https://hackage.haskell.org/package/contravariant-1.5.2/contravariant-1.5.2.tar.gz : c4262c24e3dcc2ba8ca221ed52a6390818a715301e4f13135d8d732e0c7dc60c
license    : BSD-3-Clause
component  : programming.haskell
summary    : Contravariant functors
description: |
    Contravariant functors
builddeps  :
    - haskell-cabal-install
    - haskell-StateVar-devel
    - haskell-void-devel
rundeps    :
    - devel:
        - haskell-StateVar-devel
        - haskell-void-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register

